#!/bin/bash

input=${1::-4}_mc.nii
anat=$2

inputa=$anat
inputam=${anat::-4}_msc_man.nii
inputf=${input::-4}_mean.nii
inputfm=${input::-4}_msc_man.nii

DIR=$(dirname $inputf)
reganat=$DIR/reg_anat

mkdir -p $reganat

sct_register_multimodal \
	-i $inputf \
	-d $inputa \
	-iseg $inputfm \
	-dseg $inputam \
	-param step=1,type=seg,algo=centermass,metric=MeanSquares,slicewise=1,smooth=3:step=2,type=seg,algo=bsplinesyn,metric=MeanSquares,slicewise=1,iter=10 \
	-x spline \
	-ofolder $reganat \
	-owarp $reganat/warp_epi2megre.nii.gz \
  -owarpinv $reganat/warp_megre2epi.nii.gz

gzip -f $reganat/*.nii

# Warp tsnr image to anat space
sct_apply_transfo \
 -i ${input::-4}_tsnr.nii \
 -d $inputa \
 -w $reganat/warp_epi2megre.nii.gz \
 -o $reganat/tsnr2anat.nii.gz
