#!/bin/bash

input=$1

DIR=$(dirname $input)
DIRstats=$DIR/lvl1.feat/stats
DIRold=$DIR/reg_anat/stats_old
DIRregstd=$DIR/lvl1.feat/reg_standard

inputd=$2
inputw=$DIR/reg_anat/warp_epi2megre.nii.gz


sct_apply_transfo \
  -i $DIRold/zfstat1.nii.gz \
  -d $inputd \
  -w $inputw \
  -o $DIRstats/zfstat1.nii.gz

sct_apply_transfo \
  -i $DIRold/zstat1.nii.gz \
  -d $inputd \
  -w $inputw \
  -o $DIRstats/zstat1.nii.gz

sct_apply_transfo \
  -i $DIRold/zstat2.nii.gz \
  -d $inputd \
  -w $inputw \
  -o $DIRstats/zstat2.nii.gz

sct_apply_transfo \
  -i $DIRold/zstat3.nii.gz \
  -d $inputd \
  -w $inputw \
  -o $DIRstats/zstat3.nii.gz

mkdir -p $DIRregstd/reg
mkdir -p $DIRregstd/stats

sct_apply_transfo \
  -i $DIR/lvl1.feat/example_func.nii.gz \
  -d $inputd \
  -w $inputw \
  -o $DIRregstd/example_func.nii.gz

sct_apply_transfo \
  -i $DIR/lvl1.feat/mean_func.nii.gz \
  -d $inputd \
  -w $inputw \
  -o $DIRregstd/mean_func.nii.gz


sct_apply_transfo \
  -i $DIRstats/cope1.nii.gz \
  -d $inputd \
  -w $inputw \
  -o $DIRregstd/stats/cope1.nii.gz

sct_apply_transfo \
  -i $DIRstats/cope2.nii.gz \
  -d $inputd \
  -w $inputw \
  -o $DIRregstd/stats/cope2.nii.gz

sct_apply_transfo \
  -i $DIRstats/cope3.nii.gz \
  -d $inputd \
  -w $inputw \
  -o $DIRregstd/stats/cope3.nii.gz


sct_apply_transfo \
  -i $DIRstats/varcope1.nii.gz \
  -d $inputd \
  -w $inputw \
  -o $DIRregstd/stats/varcope1.nii.gz

sct_apply_transfo \
  -i $DIRstats/varcope2.nii.gz \
  -d $inputd \
  -w $inputw \
  -o $DIRregstd/stats/varcope2.nii.gz

sct_apply_transfo \
  -i $DIRstats/varcope3.nii.gz \
  -d $inputd \
  -w $inputw \
  -o $DIRregstd/stats/varcope3.nii.gz

updatefeatreg $(dirname $DIRstats) -gifs
