#!/bin/bash

DIR=$1

cope_ovs68=func/derivatives/ovs_pf68/lvl2template.feat/stats/cope1.nii.gz
cope_zmit68=func/derivatives/zoomit_pf68/lvl2template.feat/stats/cope1.nii.gz
cope_zmit78=func/derivatives/zoomit_pf78/lvl2template.feat/stats/cope1.nii.gz
cope_zmitno=func/derivatives/zoomit_pfno/lvl2template.feat/stats/cope1.nii.gz

DIR_grp=$DIR/grplvl_noise

mask=$DIR_grp/PAM50_cord_cr.nii.gz
sct_crop_image \
  -i $SCT_DIR/data/PAM50/template/PAM50_cord.nii.gz  \
  -zmin 50 -zmax 231 \
  -o $mask


# -------------------------------------------------------------------------------------------------------------

cope1=$DIR/sub-03n/$cope_ovs68
cope2=$DIR/sub-03n/$cope_zmit68
cope3=$DIR/sub-03n/$cope_zmit78
cope4=$DIR/sub-03n/$cope_zmitno

cope5=$DIR/sub-06n/$cope_ovs68
cope6=$DIR/sub-06n/$cope_zmit68
cope7=$DIR/sub-06n/$cope_zmit78
cope8=$DIR/sub-06n/$cope_zmitno

cope9=$DIR/sub-13n/$cope_ovs68
cope10=$DIR/sub-13n/$cope_zmit68
cope11=$DIR/sub-13n/$cope_zmit78
cope12=$DIR/sub-13n/$cope_zmitno


sct_image \
  -i $cope1 $cope2 $cope3 $cope4 $cope5 $cope6 $cope7 $cope8 $cope9 $cope10 $cope11 $cope12 \
  -concat t \
  -o $DIR_grp/noise_cope_concat.nii

sct_crop_image \
  -i $DIR_grp/noise_cope_concat.nii \
  -zmin 50  -zmax 231 \
  -o $DIR_grp/noise_cope_concat_cr.nii

randomise \
  -i $DIR_grp/noise_cope_concat_cr.nii \
  -o $DIR_grp/noise \
  -m $mask \
  -1 -v 5 -T




DIR_grp_results=$DIR_grp/00_results
rm -rf $DIR_grp_results
mkdir -p $DIR_grp_results


sct_crop_image \
  -i $DIR_grp/noise_tstat1.nii.gz \
  -xmin 55 -xmax 85 \
  -ymin 55 -ymax 85 \
  -o $DIR_grp_results/noise_tstat1_cr.nii

sct_crop_image \
  -i $DIR_grp/noise_tfce_corrp_tstat1.nii.gz \
  -xmin 55 -xmax 85 \
  -ymin 55 -ymax 85 \
  -o $DIR_grp_results/noise_tfce_corrp_tstat1_cr.nii


sct_crop_image \
  -i $SCT_DIR/data/PAM50/template/PAM50_cord.nii.gz \
  -xmin 55 -xmax 85 \
  -ymin 55 -ymax 85 \
  -zmin 50 -zmax 231 \
  -o $DIR_grp_results/PAM50_cord_cr.nii

sct_crop_image \
  -i $SCT_DIR/data/PAM50/template/PAM50_t2.nii.gz \
  -xmin 55 -xmax 85 \
  -ymin 55 -ymax 85 \
  -zmin 50 -zmax 231 \
  -o $DIR_grp_results/PAM50_t2_cr.nii
